version: '2'
services:
### Workspace Utilities Container ###########################
    workspace:
        build: vm/workspace
        volumes:
            - ./:/var/www
        tty: true
        environment:
            - NODE_ENV=development
        ports:
            - "4200:4200"
            - "1337:1337"
### Databases Data Container ################################
    data:
        build: vm/data
        volumes:
            - /var/lib/mongo:/data/db
### MongoDB Container #######################################
    mongo:
        build: vm/services/mongo
        ports:
            - "27017:27017"
        volumes_from:
            - data
# ### Add more Containers below ###############################