# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
require 'fileutils'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Custom Settings
#env = YAML.load_file 'env.yml'
ENV_FILE = File.join(File.dirname(__FILE__), 'env.yml')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Custom Configuration
    if File.exist?(ENV_FILE)
        env_config = YAML.load_file 'env.yml'


        # Proxy Settings
        if env_config['proxy']['enabled'] == true
            config.proxy.http = env_config['proxy']['http']
            config.proxy.https = env_config['proxy']['https']
            config.proxy.no_proxy = env_config['proxy']['no_proxy']
        end
    end

    # box to build virtual evironment to build off of.
    config.vm.box = "ubuntu/trusty64" # Ubuntu 14.04 LTS

    # configurating the vm
    config.vm.provider "virtualbox" do |v|
        # GUI settings
        v.gui = false
        # VM Name
        v.name = "SailsAPP"
        # max 75% CPU cap
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
        # 512MB ram
        v.memory = 512
    end

    # run "bootstrap.sh" shell script when setting up our machine
    config.vm.provision :shell, :privileged => false, :path => "bootstrap.sh"


    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network "private_network", ip: "192.168.100.100"
    config.vm.network "forwarded_port", host: 3000, guest: 3000, auto_correct: true    # Node
    config.vm.network "forwarded_port", guest: 27019, host: 27019, auto_correct: true  # MongoDB
    config.vm.network "forwarded_port", host: 4200, guest: 4200, auto_correct: true    # angular server
    config.vm.network "forwarded_port", host: 1337, guest: 1337, auto_correct: true    # SailsJS

    # Shared folder
    config.vm.synced_folder "../", "/home/vagrant",
    id: "vagrant-root",
    owner: "vagrant",
    create: "true",
    group: "vagrant",
    disabled: false
end
